/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeup.mini.tienda.ui.console;

import com.codeup.mini.tienda.domain.products;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Coder
 */
public class InventanrioFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventanrioFrame.class.getName());
    private products productManager = new products();

    /**
     * Creates new form InventanrioFrame
     */
    public InventanrioFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventario = new javax.swing.JTable();
        lblProduct = new javax.swing.JTextField();
        lblStock = new javax.swing.JTextField();
        spinnerPrice = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        searchProduct = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        lblBuyProduct = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonstactisc = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Productos", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tableInventario);

        lblProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Producto");

        jLabel2.setText("Cantidad");

        jLabel5.setText("Precio");

        jButton2.setText("Buscar producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Comprar producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblQuantityActionPerformed(evt);
            }
        });

        jLabel3.setText("Producto");

        jLabel4.setText("Cantidad");

        jLabel6.setText("Producto");

        buttonstactisc.setText("Estadisticas");
        buttonstactisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonstactiscActionPerformed(evt);
            }
        });

        buttonExit.setText("Salir");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(spinnerPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStock, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel5))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblBuyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonExit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(46, 46, 46)
                                .addComponent(buttonstactisc)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(buttonstactisc))
                .addGap(138, 138, 138)
                .addComponent(buttonExit)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void inicializarTabla(){
        tableInventario.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] { "Productos", "Precio", "Stock"
        }
     ));
    }
    
    private void actualizarTabla(){
        var modelo = (javax.swing.table.DefaultTableModel) tableInventario.getModel();
        modelo.setRowCount(0);
        for (Object[] fila : productManager.listarProductos()) {
            modelo.addRow(fila);
        }
}
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        String nameProduct = lblProduct.getText();
        double price = Double.parseDouble(spinnerPrice.getValue().toString());
        int quantity = Integer.parseInt(lblStock.getText());

        if (nameProduct.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre del producto no puede estar vacío");
            return;
        }

        if (price  == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "El precio no puede ser cero");
        }

        // Agregar producto al manager
        productManager.addProduct(nameProduct, price, quantity);

        actualizarTabla();

        // Limpiar campos
        lblProduct.setText("");
        lblStock.setText("");
        spinnerPrice.setValue(0);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Precio o cantidad inválidos");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProductActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            String search = searchProduct.getText().toString();
            boolean encontrado = false;
            
            for (Object[] fila : productManager.listarProductos()){
                String nombre = fila[0].toString();
                
                if (nombre.equalsIgnoreCase(search)){
                    encontrado = true;
                    break;
                }
            }
            
            if (encontrado){
                javax.swing.JOptionPane.showMessageDialog(this, "El producto se encuentra en la lista");
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "El producto no se encuentra en la lista");
            }
            
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un valo valido");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            
            String buy = lblBuyProduct.getText().toString();
            int quantity = Integer.parseInt(lblQuantity.getText().trim());
            
            
            boolean success = productManager.buyProduct(buy, quantity);
            boolean successRegister = productManager.generateTickect(buy, quantity);
            
            if (success){
                javax.swing.JOptionPane.showMessageDialog(this, "Compra realizada correctamente");
                actualizarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se realizo la compra");
            }
            
            
        }catch (NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa una cantidad numerica");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lblQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuantityActionPerformed

    private void buttonstactiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonstactiscActionPerformed
var model = (javax.swing.table.DefaultTableModel) tableInventario.getModel();
    model.setRowCount(0); // Limpiar tabla

    for (Object[] fila : productManager.getPrices()) {
        model.addRow(fila);
    }    }//GEN-LAST:event_buttonstactiscActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        
        
        try {
                String buy  = lblBuyProduct.getText().trim();
                int quantity = Integer.parseInt(lblQuantity.getText().trim());

                //Motsrar ticket
                String summary = productManager.tickectCheck();
                javax.swing.JOptionPane.showMessageDialog(this, summary);

                //Cerrar ventana
                dispose();
            } catch(NumberFormatException e){
                javax.swing.JOptionPane.showMessageDialog(this, "El ticket no fue encontrado");
                    }   
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventanrioFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonstactisc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblBuyProduct;
    private javax.swing.JTextField lblProduct;
    private javax.swing.JTextField lblQuantity;
    private javax.swing.JTextField lblStock;
    private javax.swing.JTextField searchProduct;
    private javax.swing.JSpinner spinnerPrice;
    private javax.swing.JTable tableInventario;
    // End of variables declaration//GEN-END:variables
}